<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('The SMILE Project')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/png', 'href' => $this->basePath() . '/img/favicon.png'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/anr/anr.css'))
        ->prependStylesheet($this->basePath('css/material-icons.css'))
        ->prependStylesheet($this->basePath('css/angular-common-libs.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        // TODO: In Production mode, use app.min.js which is a minified version of everything below. It must be
        // generated using grunt concat/uglify task.
        // Global files
        ->appendFile($this->basePath('js/angular-common-libs.js'))
        ->appendFile($this->basePath('js/translations.js'))
        // ANR Module
        ->appendFile($this->basePath('js/anr/AnrModule.js'))
        ->appendFile($this->basePath('js/anr/AnrService.js'))
        ->appendFile($this->basePath('js/anr/AnrLayoutCtrl.js'))
        ->appendFile($this->basePath('js/anr/AnrObjectCtrl.js'))
        ->appendFile($this->basePath('js/anr/AnrObjectInstanceCtrl.js'))
        ->appendFile($this->basePath('js/anr/ObjlibService.js'))
        ->appendFile($this->basePath('js/anr/ModelService.js'))
        ->appendFile($this->basePath('js/anr/CreateObjlibDialogCtrl.js'))
        ->appendFile($this->basePath('js/anr/TagService.js'))
        ->appendFile($this->basePath('js/anr/AssetService.js'))
        ->appendFile($this->basePath('js/anr/AnrObjectResource.js'))
        ->appendFile($this->basePath('js/anr/MassDeleteService.js'))
        ->appendFile($this->basePath('js/anr/MeasureService.js'))
        ->appendFile($this->basePath('js/anr/ThreatService.js'))
        ->appendFile($this->basePath('js/anr/VulnService.js'))
        ->appendFile($this->basePath('js/anr/RiskService.js'))
        ->appendFile($this->basePath('js/anr/AmvService.js'))
        ->appendFile($this->basePath('js/anr/CategoryService.js'))
        ->appendFile($this->basePath('js/anr/ToolsAnrService.js'))
        ->appendFile($this->basePath('js/anr/DownloadService.js'))
        ->appendFile($this->basePath('js/anr/InstanceService.js'))
        ->appendFile($this->basePath('js/anr/DashNullFilter.js'))
        ->appendFile($this->basePath('js/anr/QuestionService.js'))
        // Client app files
        ->appendFile($this->basePath('js/ClientApp.js'))
        ->appendFile($this->basePath('js/UserService.js'))
        ->appendFile($this->basePath('js/UserProfileService.js'))
        ->appendFile($this->basePath('js/ClientUsersService.js'))
        ->appendFile($this->basePath('js/ConfigService.js'))
        ->appendFile($this->basePath('js/ErrorService.js'))
        ->appendFile($this->basePath('js/ClientLoginCtrl.js'))
        ->appendFile($this->basePath('js/ClientMainCtrl.js'))
        ->appendFile($this->basePath('js/ClientAccountCtrl.js'))
        ->appendFile($this->basePath('js/TableHelperService.js'))
        ->appendFile($this->basePath('js/CreateRiskAnalysisDialog.js'))
        ->appendFile($this->basePath('js/ClientAdminLogsCtrl.js'))
        ->appendFile($this->basePath('js/ClientAdminUsersCtrl.js'))
        ->appendFile($this->basePath('js/ClientPasswordForgottenCtrl.js'))
        // ANR, but client-only
        ->appendFile($this->basePath('js/anr/AnrKbMgmtCtrl.js'))
        ->appendFile($this->basePath('js/ClientAnrService.js'))
 ?>

</head>
<body ng-app="ClientApp" layout="column" flex>
<section layout="row" flex ui-view="main">
</section>

<?php echo $this->inlineScript() ?>

</body>
</html>

