<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>MONARC by Cases.lu</title>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/png', 'href' => 'img/favicon.png'))
        ->prependStylesheet(('css/style.css'))
        ->prependStylesheet(('css/anr/anr.css'))
        ->prependStylesheet(('css/material-icons.css'))
        ->prependStylesheet(('css/angular-common-libs.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        // TODO: In Production mode, use app.min.js which is a minified version of everything below. It must be
        // generated using grunt concat/uglify task.
        // Global files
        ->appendFile(('js/angular-common-libs.js'))

        ->appendFile(('js/translations.js'))
        // ANR Module
        ->appendFile(('js/anr/AnrModule.js'))
        ->appendFile(('js/anr/AnrService.js'))
        ->appendFile(('js/anr/AnrLayoutCtrl.js'))
        ->appendFile(('js/anr/AnrObjectCtrl.js'))
        ->appendFile(('js/anr/AnrObjectInstanceCtrl.js'))
        ->appendFile(('js/anr/AnrRisksPlanCtrl.js'))
        ->appendFile(('js/anr/AnrSoaCtrl.js'))
        ->appendFile(('js/anr/AnrRopaCtrl.js'))
        ->appendFile(('js/anr/AnrSoaSheetCtrl.js'))

        ->appendFile(('js/anr/AnrRisksPlanSheetCtrl.js'))
        ->appendFile(('js/anr/AnrRisksPlanHistoryCtrl.js'))
        ->appendFile(('js/anr/ObjlibService.js'))
        ->appendFile(('js/anr/ModelService.js'))
        ->appendFile(('js/anr/CreateObjlibDialogCtrl.js'))
        ->appendFile(('js/anr/RiskRecommendationPartialCtrl.js'))
        ->appendFile(('js/anr/TagService.js'))
        ->appendFile(('js/anr/AssetService.js'))
        ->appendFile(('js/anr/AnrObjectResource.js'))
        ->appendFile(('js/anr/MassDeleteService.js'))
        ->appendFile(('js/anr/MeasureService.js'))
        ->appendFile(('js/anr/MeasureMeasureService.js'))
        ->appendFile(('js/anr/ThreatService.js'))
        ->appendFile(('js/anr/VulnService.js'))
        ->appendFile(('js/anr/RecordService.js'))
        ->appendFile(('js/anr/ReferentialService.js'))
        ->appendFile(('js/anr/RiskService.js'))
        ->appendFile(('js/anr/AmvService.js'))
        ->appendFile(('js/anr/CategoryService.js'))
        ->appendFile(('js/anr/ToolsAnrService.js'))
        ->appendFile(('js/anr/DownloadService.js'))
        ->appendFile(('js/anr/InstanceService.js'))
        ->appendFile(('js/anr/DashNullFilter.js'))
        ->appendFile(('js/anr/EditableDirective.js'))
        ->appendFile(('js/anr/QuestionService.js'))
        ->appendFile(('js/anr/GuideService.js'))
        // Client app files
        ->appendFile(('js/ClientApp.js'))
        ->appendFile(('js/UserService.js'))
        ->appendFile(('js/UserProfileService.js'))
        ->appendFile(('js/ClientUsersService.js'))
        ->appendFile(('js/ConfigService.js'))
        ->appendFile(('js/ErrorService.js'))
        ->appendFile(('js/ClientLoginCtrl.js'))
        ->appendFile(('js/ClientMainCtrl.js'))
        ->appendFile(('js/ClientDashboardCtrl.js'))
        ->appendFile(('js/ClientAccountCtrl.js'))
        ->appendFile(('js/TableHelperService.js'))
        ->appendFile(('js/CreateRiskAnalysisDialog.js'))
        ->appendFile(('js/ClientAdminLogsCtrl.js'))
        ->appendFile(('js/ClientAdminUsersCtrl.js'))
        ->appendFile(('js/DeliveriesModelsCtrl.js'))
        ->appendFile(('js/DeliveriesModelsService.js'))
        ->appendFile(('js/ClientPasswordForgottenCtrl.js'))
        ->appendFile(('js/ClientSnapshotService.js'))
        ->appendFile(('js/ClientInterviewService.js'))
        ->appendFile(('js/ClientRecommandationService.js'))
        ->appendFile(('js/TreatmentPlanService.js'))
        ->appendFile(('js/ClientSoaService.js'))
        ->appendFile(('js/anr/SOACategoryService.js'))
        // ANR, but client-only
        ->appendFile(('js/anr/AnrKbMgmtCtrl.js'))
        ->appendFile(('js/ClientAnrService.js'))
        // // Dashboard Library
        ->appendFile(('js/ChartService.js'))
        ->appendFile(('js/MultiVerticalBarChartService.js'))
        ->appendFile(('js/VerticalBarChartService.js'))
        ->appendFile(('js/MultiHorizontalBarChartService.js'))
        ->appendFile(('js/HorizontalBarChartService.js'))
        ->appendFile(('js/LineChartService.js'))
        ->appendFile(('js/RadarChartService.js'))
        ->appendFile(('js/HeatmapChartService.js'))
        ->appendFile(('js/DonutChartService.js'))


 ?>

</head>
<body md-no-ink ng-app="ClientApp" layout="column" flex>
<section layout="row" flex ui-view="main">
</section>

<?php echo $this->inlineScript() ?>

</body>
</html>
